language: python
services:
  - mysql
python:
  - "3.6"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diagnostics;'
  - mysql -u root < schema.sql
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
notifications:
  email:
    recipients:
      - gadilif@gmail.com
    on_success: change # default: change, can also be never
    on_failure: always # default: always